In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import pandas as pd
pd.set_option('display.max_rows', None)

In [4]:
import os
ROOT = r'C:\\Users\\an_em\\LocalDrive\\Projects\\arvadasermons'
os.chdir(ROOT)

In [5]:
from lib.load_data import load_data

In [15]:
df = load_data()
# df = df[~(df['series']=='Bonus Episode')]

cols = ['date', 'year', 'title', 'description', 'title_n_splits', 'series',
       'episode_label', 'speaker']

df[cols].head(10)

,date,year,title,description,title_n_splits,series,episode_label,speaker
0,2026-04-26,2026,Restored | Step 10 | Sarah O'Connor | Mile Hig...,Restored | Step 10 | Sarah O'Connor | Mile Hig...,4,Restored,Step 10,Sarah O'Connor
1,2026-04-19,2026,Restored | Step 9 | Becca Knudsen | Mile High ...,Restored | Step 9 | Becca Knudsen | Mile High ...,4,Restored,Step 9,Becca Knudsen
2,2026-04-12,2026,Restored | Step 8 | Tom White | Mile High Vine...,Restored | Step 8 | Tom White | Mile High Vine...,4,Restored,Step 8,Tom White
4,2026-04-05,2026,Restored | Step 7 | Jay Pathak | Mile High Vin...,Restored | Step 7 | Jay Pathak | Mile High Vin...,4,Restored,Step 7,Jay Pathak
5,2026-03-29,2026,Restored | Step 6 | Jay Pathak | Mile High Vin...,Restored | Step 6 | Jay Pathak | Mile High Vin...,4,Restored,Step 6,Jay Pathak
6,2026-03-22,2026,Restored | Step 4 | Ben Folman | Mile High Vin...,None,4,Restored,Step 4,Ben Folman
7,2026-03-15,2026,Restored | Step 5 | Jay Pathak | Mile High Vin...,None,4,Restored,Step 5,Jay Pathak
8,2026-03-08,2026,Restored | Step 3 | Andy Masters | Mile High V...,Restored | Step 3 | Andy Masters | Mile High V...,4,Restored,Step 3,Andy Masters
9,2026-03-01,2026,Restored | Step 2: Believe | Jay Pathak | Mile...,Restored | Step 2: Believe | Jay Pathak | Mile...,4,Restored,Step 2: Believe,Jay Pathak
10,2026-02-27,2026,Restored | Step 1: Admit | Jay Pathak | Mile H...,None,4,Restored,Step 1: Admit,Jay Pathak

In [16]:
df[df['speaker']=="[not available]"]

,date,year,title,episode_page,audio_url,episode_id,dest_id,category,description,title_n_splits,series,episode_label,speaker
206,2022-04-15,2022,"LENT 2022 Daily Devotional: Friday, April 15th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22245092,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Friday, April 15th",[not available]
207,2022-04-14,2022,"LENT 2022 Daily Devotional: Thursday, April 14th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22245053,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Thursday, April 14th",[not available]
208,2022-04-13,2022,"LENT 2022 Daily Devotional: Wednesday, April 13th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22245047,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Wednesday, April 13th",[not available]
209,2022-04-12,2022,"LENT 2022 Daily Devotional: Tuesday, April 12th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22245017,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Tuesday, April 12th",[not available]
210,2022-04-11,2022,"LENT 2022 Daily Devotional: Monday, April 11th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244993,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Monday, April 11th",[not available]
212,2022-04-08,2022,"LENT 2022 Daily Devotional: Friday, April 8th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244948,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Friday, April 8th",[not available]
213,2022-04-07,2022,"LENT 2022 Daily Devotional: Thursday, April 7th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244897,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Thursday, April 7th",[not available]
214,2022-04-06,2022,"LENT 2022 Daily Devotional: Wednesday, April 6th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244879,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Wednesday, April 6th",[not available]
215,2022-04-05,2022,"LENT 2022 Daily Devotional: Tuesday, April 5th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244849,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Tuesday, April 5th",[not available]
216,2022-04-04,2022,"LENT 2022 Daily Devotional: Monday, April 4th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244795,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Monday, April 4th",[not available]
218,2022-04-01,2022,"LENT 2022 Daily Devotional: Friday, April 1st",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244759,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Friday, April 1st",[not available]
219,2022-03-31,2022,"LENT 2022 Daily Devotional: Thursday, March 31st",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244738,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Thursday, March 31st",[not available]
220,2022-03-30,2022,"LENT 2022 Daily Devotional: Wednesday, March 30th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244690,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Wednesday, March 30th",[not available]
221,2022-03-29,2022,"LENT 2022 Daily Devotional: Tuesday, March 29th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244663,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Tuesday, March 29th",[not available]
222,2022-03-28,2022,"LENT 2022 Daily Devotional: Monday, March 28th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244642,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Monday, March 28th",[not available]
224,2022-03-25,2022,"LENT 2022 Daily Devotional: Friday, March 25th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244585,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Friday, March 25th",[not available]
225,2022-03-24,2022,"LENT 2022 Daily Devotional: Thursday, March 24th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244543,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Thursday, March 24th",[not available]
226,2022-03-23,2022,"LENT 2022 Daily Devotional: Wednesday, March 23rd",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244462,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Wednesday, March 23rd",[not available]
227,2022-03-22,2022,"LENT 2022 Daily Devotional: Tuesday, March 22nd",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244438,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Tuesday, March 22nd",[not available]
228,2022-03-21,2022,"LENT 2022 Daily Devotional: Monday, March 21st",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244420,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Monday, March 21st",[not available]
229,2022-03-20,2022,Desire Week 3: The Desire For Justice,http://milehighvineyard.libsyn.com/desire-week...,http://traffic.libsyn.com/milehighvineyard/3-2...,22582148,94476,general,None,1,,Desire Week 3: The Desire For Justice,[not available]
230,2022-03-18,2022,"LENT 2022 Daily Devotional: Friday, March 18th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244339,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Friday, March 18th",[not available]
231,2022-03-17,2022,"LENT 2022 Daily Devotional: Thursday, March 17th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244300,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Thursday, March 17th",[not available]
232,2022-03-16,2022,"LENT 2022 Daily Devotional: Wednesday, March 16th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244270,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Wednesday, March 16th",[not available]
233,2022-03-15,2022,"LENT 2022 Daily Devotional: Tuesday, March 15th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244237,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Tuesday, March 15th",[not available]
234,2022-03-14,2022,"LENT 2022 Daily Devotional: Monday, March 14th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244186,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Monday, March 14th",[not available]
235,2022-03-13,2022,Desire Week 2: The Desire For Meaning,http://milehighvineyard.libsyn.com/desire-week...,http://traffic.libsyn.com/milehighvineyard/3-1...,22472693,94476,general,None,1,,Desire Week 2: The Desire For Meaning,[not available]
236,2022-03-11,2022,"LENT 2022 Daily Devotional: Friday, March 11th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244135,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Friday, March 11th",[not available]
237,2022-03-10,2022,"LENT 2022 Daily Devotional: Thursday, March 10th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244090,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Thursday, March 10th",[not available]
238,2022-03-09,2022,"LENT 2022 Daily Devotional: Wednesday, March 9th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244069,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Wednesday, March 9th",[not available]
239,2022-03-08,2022,"LENT 2022 Daily Devotional: Tuesday, March 8th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22244039,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Tuesday, March 8th",[not available]
240,2022-03-07,2022,"LENT 2022 Daily Devotional: Monday, March 7th",http://milehighvineyard.libsyn.com/lent-2022-d...,http://traffic.libsyn.com/milehighvineyard/Day...,22243574,94476,general,Welcome to the Mile High Vineyard podcast: Len...,1,,"LENT 2022 Daily Devotional: Monday, March 7th",[not available]
242,2022-02-27,2022,Making Sense Of Faith To Skeptics,http://milehighvineyard.libsyn.com/making-sens...,http://traffic.libsyn.com/milehighvineyard/2-2...,22284464,94476,general,None,1,,Making Sense Of Faith To Skeptics,[not available]
243,2022-02-20,2022,Pandemic Ponderings: Week 2,http://milehighvineyard.libsyn.com/pandemic-po...,http://traffic.libsyn.com/milehighvineyard/2-2...,22241540,94476,general,None,1,,Pandemic Ponderings: Week 2,[not available]
247,2022-01-23,2022,BLESS Week 4: Eat,http://milehighvineyard.libsyn.com/bless-week-...,http://traffic.libsyn.com/milehighvineyard/1-2...,22014230,94476,general,None,1,,BLESS Week 4: Eat,[not available]
255,2021-11-21,2021,Every Week: Generosity,http://milehighvineyard.libsyn.com/every-week-...,http://traffic.libsyn.com/milehighvineyard/11-...,21399737,94476,general,None,1,,Every Week: Generosity,[not available]
281,2021-05-09,2021,Party Like Jesus - Week 5,http://milehighvineyard.libsyn.com/party-like-...,http://traffic.libsyn.com/milehighvineyard/MHV...,19670261,94476,general,Mother's Day,1,,Party Like Jesus - Week 5,[not available]
329,2020-06-06,2020,Finding Faith In The Wilderness Devotional - S...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Sat...,14277896,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - S...,[not available]
330,2020-06-05,2020,Finding Faith In The Wilderness Devotional - F...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Fri...,14277878,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - F...,[not available]
332,2020-06-03,2020,Finding Faith In The Wilderness Devotional - W...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Wed...,14277848,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - W...,[not available]
333,2020-06-02,2020,Finding Faith In The Wilderness Devotional - T...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Tue...,14277824,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - T...,[not available]
336,2020-05-31,2020,Finding Faith In The Wilderness Devotional - S...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Sun...,14277794,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - S...,[not available]
337,2020-05-30,2020,Finding Faith In The Wilderness Devotional - S...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Sat...,14277371,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - S...,[not available]
338,2020-05-29,2020,Finding Faith In The Wilderness Devotional - F...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Fri...,14277362,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - F...,[not available]
340,2020-05-27,2020,Finding Faith In The Wilderness Devotional - W...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Wed...,14277341,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - W...,[not available]
341,2020-05-26,2020,Finding Faith In The Wilderness Devotional - T...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Tue...,14277332,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - T...,[not available]
344,2020-05-24,2020,Finding Faith In The Wilderness Devotional - S...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Sun...,14277278,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - S...,[not available]
345,2020-05-23,2020,Finding Faith In The Wilderness Devotional - S...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Sat...,14275742,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - S...,[not available]
346,2020-05-22,2020,Finding Faith In The Wilderness Devotional - F...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Fri...,14275715,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - F...,[not available]
348,2020-05-20,2020,Finding Faith In The Wilderness Devotional - W...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Wed...,14275694,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - W...,[not available]
349,2020-05-19,2020,Finding Faith In The Wilderness Devotional - T...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Tu5...,14275673,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - T...,[not available]
352,2020-05-17,2020,Finding Faith In The Wilderness Devotional - S...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Sun...,14275628,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - S...,[not available]
353,2020-05-16,2020,Finding Faith In The Wilderness Devotional - S...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Sat...,14274923,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - S...,[not available]
354,2020-05-15,2020,Finding Faith In The Wilderness Devotional - F...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Fri...,14274908,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - F...,[not available]
356,2020-05-13,2020,Finding Faith In The Wilderness Devotional - W...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Wed...,14274869,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - W...,[not available]
357,2020-05-12,2020,Finding Faith In The Wilderness Devotional - T...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Tue...,14274857,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - T...,[not available]
360,2020-05-10,2020,Finding Faith In The Wilderness Devotional - S...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Sun...,14274818,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - S...,[not available]
361,2020-05-09,2020,Finding Faith In The Wilderness Devotional - S...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Sat...,14273351,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - S...,[not available]
362,2020-05-08,2020,Finding Faith In The Wilderness Devotional - F...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Fri...,14273327,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - F...,[not available]
364,2020-05-06,2020,Finding Faith In The Wilderness Devotional - W...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Wed...,14273273,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - W...,[not available]
365,2020-05-05,2020,Finding Faith In The Wilderness Devotional - T...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Tue...,14273240,94476,general,Thanks for joining us in our devotional called...,1,,Finding Faith In The Wilderness Devotional - T...,[not available]
366,2020-05-04,2020,Finding Faith In The Wilderness Devotional - M...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Mon...,14272736,94476,general,None,1,,Finding Faith In The Wilderness Devotional - M...,[not available]
368,2020-05-03,2020,Finding Faith In The Wilderness Devotional - S...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Sun...,14254310,94476,general,None,1,,Finding Faith In The Wilderness Devotional - S...,[not available]
369,2020-05-02,2020,Finding Faith In The Wilderness Devotional - S...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Sat...,14254304,94476,general,None,1,,Finding Faith In The Wilderness Devotional - S...,[not available]
370,2020-05-01,2020,Finding Faith In The Wilderness Devotional - F...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Fri...,14235458,94476,general,None,1,,Finding Faith In The Wilderness Devotional - F...,[not available]
371,2020-04-30,2020,Finding Faith In The Wilderness Devotional - T...,http://milehighvineyard.libsyn.com/finding-fai...,http://traffic.libsyn.com/milehighvineyard/Thu...,14218628,94476,general,None,1,,Finding Faith In The Wilderness Devotional - T...,[not available]

In [17]:
cols = ['date', 'title', 'series',
       'episode_label', 'speaker']
df[cols]

,date,title,series,episode_label,speaker
0,2026-04-26,Restored | Step 10 | Sarah O'Connor | Mile Hig...,Restored,Step 10,Sarah O'Connor
1,2026-04-19,Restored | Step 9 | Becca Knudsen | Mile High ...,Restored,Step 9,Becca Knudsen
2,2026-04-12,Restored | Step 8 | Tom White | Mile High Vine...,Restored,Step 8,Tom White
4,2026-04-05,Restored | Step 7 | Jay Pathak | Mile High Vin...,Restored,Step 7,Jay Pathak
5,2026-03-29,Restored | Step 6 | Jay Pathak | Mile High Vin...,Restored,Step 6,Jay Pathak
6,2026-03-22,Restored | Step 4 | Ben Folman | Mile High Vin...,Restored,Step 4,Ben Folman
7,2026-03-15,Restored | Step 5 | Jay Pathak | Mile High Vin...,Restored,Step 5,Jay Pathak
8,2026-03-08,Restored | Step 3 | Andy Masters | Mile High V...,Restored,Step 3,Andy Masters
9,2026-03-01,Restored | Step 2: Believe | Jay Pathak | Mile...,Restored,Step 2: Believe,Jay Pathak
10,2026-02-27,Restored | Step 1: Admit | Jay Pathak | Mile H...,Restored,Step 1: Admit,Jay Pathak
11,2026-02-15,Restored | The Path Toward Freedom | Tom White...,Restored,The Path Toward Freedom,Tom White
12,2026-02-08,Set Apart | Consecrated for Mission | Jay Pat...,Set Apart,Consecrated for Mission,Jay Pathak
13,2026-02-01,Set Apart | A Consecrated Church | Jay Pathak ...,Set Apart,A Consecrated Church,Jay Pathak and Sarah O'Connor
14,2026-01-25,Set Apart | Personal Consecration | Anabeth Mo...,Set Apart,Personal Consecration,Anabeth Morgan
15,2026-01-18,We Believe In | Sacred Life | Jay Pathak | Mil...,We Believe In,Sacred Life,Jay Pathak
16,2026-01-11,We Believe In | The Holy Spirit | Ben Folman |...,We Believe In,The Holy Spirit,Ben Folman
17,2026-01-05,We Believe In | God the Father | Tom White | M...,We Believe In,God the Father,Tom White
18,2026-01-04,We Believe In | He Will Come Again | Tom White...,We Believe In,He Will Come Again,Tom White
19,2025-12-21,We Believe In | He Will Come Again | Jay Patha...,We Believe In,He Will Come Again,Jay Pathak
20,2025-12-14,We Believe In | He Came Down for Us | Jay Path...,We Believe In,He Came Down for Us,Jay Pathak
21,2025-12-07,"We Believe In | One Lord, Jesus Christ | Becca...",We Believe In,"One Lord, Jesus Christ",Becca Knudsen
22,2025-11-30,"We Believe In | One God, the Father Almighty |...",We Believe In,"One God, the Father Almighty",Jay Pathak
23,2025-11-23,The Way We See | Christian Theism | Jay Pathak...,The Way We See,Christian Theism,Jay Pathak
24,2025-11-16,The Way We See | Postmodernism | Jay Pathak | ...,The Way We See,Postmodernism,Jay Pathak
25,2025-11-09,The Way We See | Eastern Mysticism | Jay Patha...,The Way We See,Eastern Mysticism,Jay Pathak
27,2025-11-02,The Way We See | Existentialism | Jay Pathak |...,The Way We See,Existentialism,Jay Pathak
28,2025-10-26,The Way We See | Nihilism | Jay Pathak | Mile ...,The Way We See,Nihilism,Jay Pathak
29,2025-10-19,The Way We See | Deism | Jay Pathak | Mile Hig...,The Way We See,Deism,Jay Pathak
30,2025-10-12,The Way We See | Naturalism | Ben Folman | Mil...,The Way We See,Naturalism,Ben Folman
31,2025-10-05,The Way We See | What is a Worldview | Tom Whi...,The Way We See,What is a Worldview,Tom White
32,2025-09-28,the e word | 4 | Acts 8:26–40 | Jay Pathak | M...,The E Word,4 | Acts 8:26–40,Jay Pathak
33,2025-09-21,the e word | 3 | John 9:13–34 | Jay Pathak | M...,The E Word,3 | John 9:13–34,Jay Pathak
34,2025-09-14,The E Word: 2 | Becca Knudsen | Mile High Vine...,The E Word,,Becca Knudsen
35,2025-09-07,The E Word: 1 | Jay Pathak | Mile High Vineyard,The E Word,,Jay Pathak
36,2025-08-31,No One is Left Out | Jay Pathak | Mile High Vi...,No One Is Left Out,,Jay Pathak
37,2025-08-24,Encountering the Kingdom 4 | Tom White | Mile ...,Encountering The Kingdom,,Tom White
39,2025-08-17,Encountering the Kingdom 3 | Jay Pathak | Mile...,Encountering The Kingdom,,Jay Pathak
40,2025-08-10,Encountering the Kingdom 2 | Becca Knudsen | M...,Encountering The Kingdom,,Becca Knudsen
41,2025-08-03,Encountering the Kingdom | Anabeth Morgan | Mi...,Encountering The Kingdom,,Anabeth Morgan
43,2025-07-27,Beauty From Ashes 4 | Job Epilogue | Ben Folma...,Beauty From Ashes,Job Epilogue,Ben Folman
44,2025-07-20,Beauty From Ashes 3 | Job 38-42 | Tom White | ...,Beauty From Ashes,Job 38-42,Tom White
45,2025-07-13,Beauty From Ashes 2 | Job 2:10-42 | Jay Pathak...,Beauty From Ashes,Job 2:10-42,Jay Pathak
46,2025-07-06,Beauty From Ashes 1 | Job 1-2:10 | Anabeth Mor...,Beauty From Ashes,Job 1-2:10,Anabeth Morgan
48,2025-06-29,Where Did They All Go? 10 | Jay Pathak | Mile ...,Where Did They All Go?,,Jay Pathak
49,2025-06-22,"Where Did They All Go? 9 | Luke, Romans, John ...",Where Did They All Go?,"Luke, Romans, John",Jay Pathak
50,2025-06-15,Where Did They All Go? 8 | John | Becca Knudse...,Where Did They All Go?,John,Becca Knudsen
51,2025-06-08,Where Did They All Go? 7 | John | Jay Pathak |...,Where Did They All Go?,John,Jay Pathak
52,2025-06-01,Where Did They All Go? 6 | John 1:43–51 | Anab...,Where Did They All Go?,John 1:43–51,Anabeth Morgan
53,2025-05-25,Where Did They All Go? 5 | 1 John 4:7-19 | Tom...,Where Did They All Go?,1 John 4:7-19,Tom White
54,2025-05-18,"Where Did They All Go? 4 | Mark, Luke, Matthew...",Where Did They All Go?,"Mark, Luke, Matthew, Acts",Jay Pathak
55,2025-05-11,Where Did They All Go? 3 | Matthew 20:20–28 | ...,Where Did They All Go?,Matthew 20:20–28,Jay Pathak
56,2025-05-04,Where Did They All Go? | John | Jay Pathak | M...,Where Did They All Go?,John,Jay Pathak
57,2025-04-27,Where Did They All Go? | Matthew | Jay Pathak ...,Where Did They All Go?,Matthew,Jay Pathak
58,2025-04-20,Easter Sunday: A New Beginning | John 20 | Jay...,Easter Sunday A New Beginning,John 20,Jay Pathak
59,2025-04-13,Lent: Famous Last Words 6 | John 18 | Becca Kn...,Lent Famous Last Words,John 18,Becca Knudsen
60,2025-04-06,Lent: Famous Last Words 5 | John 17 | Jay Path...,Lent Famous Last Words,John 17,Jay Pathak
61,2025-03-30,Lent: Famous Last Words 4 | John 16 | Anabeth ...,Lent Famous Last Words,John 16,Anabeth Morgan
62,2025-03-23,Lent: Famous Last Words 3 | John 15 | Tom Whit...,Lent Famous Last Words,John 15,Tom White
63,2025-03-16,Lent: Famous Last Words | John 14 | Jay Pathak...,Lent Famous Last Words,John 14,Jay Pathak
64,2025-03-09,Lent: Famous Last Words | John 13 | Jay Pathak...,Lent Famous Last Words,John 13,Jay Pathak
65,2025-02-23,Modern Day Psalms 5 | Psalm 37 | Jay Pathak | ...,Modern Day Psalms,Psalm 37,Jay Pathak
66,2025-02-16,What Faith Looks Like | Genesis 18 | Eleanor M...,What Faith Looks Like,Genesis 18,Eleanor Mumford
67,2025-02-09,Modern Day Psalms 4 | Psalm 139 | Anabeth Morg...,Modern Day Psalms,Psalm 139,Anabeth Morgan
68,2025-02-02,Modern Day Psalms | Psalm 55 | Jay Pathak | Mi...,Modern Day Psalms,Psalm 55,Jay Pathak
69,2025-01-26,Modern Day Psalms 2 | Tom White | Mile High Vi...,Modern Day Psalms,,Tom White
70,2025-01-19,Modern Day Psalms | Psalm 13:1-2 | Tom White |...,Modern Day Psalms,Psalm 13:1-2,Tom White
71,2025-01-12,"Sunday Service | January 12th, 2025 | Jay Path...",Sunday Service,"January 12th, 2025",Jay Pathak
72,2025-01-05,Sunday Service | Jay Pathak | Mile High Vineyard,Sunday Service,,Jay Pathak
73,2024-12-29,New Years Service | Jay Pathak | Mile High Vin...,New Years Service,,Jay Pathak
74,2024-12-22,Advent: A Thrill of Hope 4 | Habakkuk 3 | Tom ...,Advent A Thrill Of Hope,Habakkuk 3,Tom White
75,2024-12-15,Advent: A Thrill of Hope 3 | Habakkuk 2:1-20 |...,Advent A Thrill Of Hope,Habakkuk 2:1-20,Jay Pathak
76,2024-12-08,"Advent: A Thrill of Hope 2 | Habakkuk 1:5, 12-...",Advent A Thrill Of Hope,"Habakkuk 1:5, 12-13",Kirk Yamaguchi
77,2024-12-01,Advent: A Thrill of Hope 1 | Habakkuk 1:1-4 | ...,Advent A Thrill Of Hope,Habakkuk 1:1-4,Jay Pathak
78,2024-11-24,Fruit of the Spirit 7 | Galatians 5:16 | Anabe...,Fruit Of The Spirit,Galatians 5:16,Anabeth Morgan
79,2024-11-17,Fruit of the Spirit 6 | Galatians 5:22-23 | Ja...,Fruit Of The Spirit,Galatians 5:22-23,Jay Pathak
80,2024-11-03,Fruit of the Spirit 4 | Galatians 5:15 | Danie...,Fruit Of The Spirit,Galatians 5:15,Danielle Pathak
81,2024-10-27,Fruit of the Spirit 3 | Galatians 5:5 | Tom Wh...,Fruit Of The Spirit,Galatians 5:5,Tom White
82,2024-10-20,Fruit of the Spirit 2 | Galatians 5:22-24 | Ja...,Fruit Of The Spirit,Galatians 5:22-24,Jay Pathak
83,2024-10-06,The Eyes We Need | John 4:13-14 | Kirk Yamaguc...,The Eyes We Need,John 4:13-14,Kirk Yamaguchi
84,2024-09-29,The Eyes We Need | Galatians 3:28-29 | Tom Whi...,The Eyes We Need,Galatians 3:28-29,Tom White
85,2024-09-22,The Eyes We Need | Philippians 2:14-16 & 1 Cor...,The Eyes We Need,Philippians 2:14-16 & 1 Corinthians 9:19-23,Jay Pathak
86,2024-08-25,Family Mess 13 | Genesis 37 | Jay Pathak | Mil...,Family Mess,Genesis 37,Jay Pathak
87,2024-08-25,Family Mess 14 | Genesis 41-50 | Kirk Yamaguch...,Family Mess,Genesis 41-50,Kirk Yamaguchi
88,2024-08-18,Family Mess 12 | Genesis 29:14-30 | Jay Pathak...,Family Mess,Genesis 29:14-30,Jay Pathak
89,2024-08-11,Family Mess 11 | Genesis 28:10-22 | Jay Pathak...,Family Mess,Genesis 28:10-22,Jay Pathak
90,2024-08-04,Family Mess 10 | Genesis 26:1-33 | Tom White |...,Family Mess,Genesis 26:1-33,Tom White
91,2024-07-28,Family Mess 9 | Genesis 23 & 25:1-11 | Jay Pat...,Family Mess,Genesis 23 & 25:1-11,Jay Pathak
92,2024-07-21,Family Mess 8 | Genesis 22:1-19 | Jay Pathak |...,Family Mess,Genesis 22:1-19,Jay Pathak
93,2024-07-14,Family Mess 7 | Genesis 20:1-18 | Tom White,Family Mess,Genesis 20:1-18,Tom White
94,2024-07-07,Family Mess 6 | Genesis 15:1-21 | Jay Pathak,Family Mess,Genesis 15:1-21,Jay Pathak
95,2024-06-30,Family Mess 5 | Genesis 12:1-4 | Anabeth Morgan,Family Mess,Genesis 12:1-4,Anabeth Morgan
96,2024-06-23,Family Mess 4 | Genesis 11 | Jay Pathak,Family Mess,Genesis 11,Jay Pathak
97,2024-06-16,Family Mess 3 | Genesis 3 | Kirk Yamaguchi,Family Mess,Genesis 3,Kirk Yamaguchi
98,2024-06-09,Family Mess 2 | Genesis 2 | Tom White,Family Mess,Genesis 2,Tom White
99,2024-06-04,Family Mess 1 | Genesis 1 | Becca Knudsen,Family Mess,Genesis 1,Becca Knudsen
100,2024-05-26,Serving In A Church | Jay Pathak | Mile High V...,Serving In A Church,,Jay Pathak
101,2024-05-19,Mealtime With Jesus 7 | Enacted Promise | Tom ...,Mealtime With Jesus,Enacted Promise,Tom White
102,2024-05-12,Mealtime With Jesus | Enacted Salvation | Joel...,Mealtime With Jesus,Enacted Salvation,Joel Seymour
103,2024-05-05,Mealtime With Jesus | Enacted Mission | Anabet...,Mealtime With Jesus,Enacted Mission,Anabeth Morgan
104,2024-04-28,Mealtime With Jesus | Enacted Hope | Tom White,Mealtime With Jesus,Enacted Hope,Tom White
105,2024-04-21,Mealtime With Jesus | Enacted Community | Ryan...,Mealtime With Jesus,Enacted Community,Ryan Rowlette
106,2024-04-14,Mealtime With Jesus | Enacted Grace | Jay Pathak,Mealtime With Jesus,Enacted Grace,Jay Pathak
107,2024-04-07,Mealtime With Jesus | Jesus and Meals | Tom White,Mealtime With Jesus,Jesus and Meals,Tom White
108,2024-03-31,Easter Service 2024 | Jay Pathak | Mile High V...,Easter Service 2024,,Jay Pathak
109,2024-03-24,LENT 2024 | John 8 | Tom White,Lent 2024,John 8,Tom White
110,2024-03-17,LENT 2024 | John 6 | Todd Bryski,Lent 2024,John 6,Todd Bryski
111,2024-03-10,LENT 2024 | John 5 | Ryan Rowlette,Lent 2024,John 5,Ryan Rowlette
112,2024-03-03,LENT 2024 | John 4 | Jay Pathak,Lent 2024,John 4,Jay Pathak
113,2024-02-25,LENT 2024 | John 3 | Anabeth Morgan,Lent 2024,John 3,Anabeth Morgan
114,2024-02-18,LENT 2024 | John 2 | Jay Pathak,Lent 2024,John 2,Jay Pathak
115,2024-02-04,Reset | Living for the Lost | Jay Pathak,Reset,Living for the Lost,Jay Pathak
116,2024-01-28,Reset | Kingdom Of God | Jay Pathak,Reset,Kingdom Of God,Jay Pathak
117,2024-01-21,Reset | Collaboration | Tom White,Reset,Collaboration,Tom White
118,2024-01-14,Reset | Personal Responsibility | Corey Garris,Reset,Personal Responsibility,Corey Garris
119,2024-01-07,Reset | MHV Values | Jay Pathak,Reset,MHV Values,Jay Pathak
120,2023-12-17,Advent 2023 | John The Baptist | Brittany Kurtz,Advent 2023,John The Baptist,Brittany Kurtz
121,2023-12-10,Advent 2023 | Waiting & Longing | Corey Garris,Advent 2023,Waiting & Longing,Corey Garris
122,2023-12-03,Advent 2023 | Chronos & Kairos Time | Jay Pathak,Advent 2023,Chronos & Kairos Time,Jay Pathak
123,2023-11-26,Don't Die Dumb | Finding Wisdom | Corey Garris,Don't Die Dumb,Finding Wisdom,Corey Garris
124,2023-11-19,Don't Die Dumb | Generosity | Anabeth Morgan,Don't Die Dumb,Generosity,Anabeth Morgan
125,2023-11-12,Don't Die Dumb | Offense | Corey Garris,Don't Die Dumb,Offense,Corey Garris
126,2023-11-05,Don't Die Dumb | Grey Hair | David Parker,Don't Die Dumb,Grey Hair,David Parker
127,2023-10-29,Don't Die Dumb | Quick Fixes | Jay Pathak,Don't Die Dumb,Quick Fixes,Jay Pathak
128,2023-10-22,I Pledge Allegiance: Week 7 By Corey Garris,,I Pledge Allegiance: Week 7,Corey Garris
129,2023-10-15,I Pledge Allegiance: Week 6 By Tom White,,I Pledge Allegiance: Week 6,Tom White
130,2023-10-08,I Pledge Allegiance: Week 5 By Corey Garris,,I Pledge Allegiance: Week 5,Corey Garris
131,2023-10-01,I Pledge Allegiance: Week 4 By Jay Pathak,,I Pledge Allegiance: Week 4,Jay Pathak
132,2023-09-24,I Pledge Allegiance: Week 3 By Corey Garris,,I Pledge Allegiance: Week 3,Corey Garris
133,2023-09-17,I Pledge Allegiance: Week 2 By Tom White,,I Pledge Allegiance: Week 2,Tom White
134,2023-09-10,I Pledge Allegiance: Week 1 By Corey Garris,,I Pledge Allegiance: Week 1,Corey Garris
135,2023-09-03,Vineyard Values: Community by Ryan Rowlette,,Vineyard Values: Community,Ryan Rowlette
136,2023-08-27,Vineyard Values: God's Heart for the Nations B...,,Vineyard Values: God's Heart for the Nations,Corey Garris
137,2023-08-20,Vineyard Values: Worship by Cyndia Garris,,Vineyard Values: Worship,Cyndia Garris
138,2023-08-13,Vineyard Values: Justice & City Partnerships b...,,Vineyard Values: Justice & City Partnerships,Jay Pathak
139,2023-08-06,Parables 9: Clean & Unclean By Brittany Kurtz,,Parables 9: Clean & Unclean,Brittany Kurtz
140,2023-07-30,Parables 8: Fig Tree - By Corey Garris,,Parables 8: Fig Tree,Corey Garris
141,2023-07-23,Parables 7: Tenants - By Jay Pathak,,Parables 7: Tenants,Jay Pathak
142,2023-07-16,Parables 6: Mustard Seed - By Todd Bryski,,Parables 6: Mustard Seed,Todd Bryski
143,2023-07-09,Parables 5: Growing Seed - By Corey Garris,,Parables 5: Growing Seed,Corey Garris
144,2023-07-02,Parables 4: Lamp - By Anabeth Morgan,,Parables 4: Lamp,Anabeth Morgan
145,2023-06-25,Parables 3: Sower - By Jay Pathak,,Parables 3: Sower,Jay Pathak
146,2023-06-18,Parables 2: The Strong Man - By Corey Garris,,Parables 2: The Strong Man,Corey Garris
147,2023-06-11,Parables 1: Intro To The Parables - By Jay Pathak,,Parables 1: Intro To The Parables,Jay Pathak
148,2023-06-04,Loving Jesus & Speaking His Name - By Corey Ga...,,Loving Jesus & Speaking His Name,Corey Garris
149,2023-05-28,Empowered 7: Pentecost Sunday - By Jay Pathak,,Empowered 7: Pentecost Sunday,Jay Pathak
150,2023-05-21,Empowered 6: Authority - By Anabeth Morgan,,Empowered 6: Authority,Anabeth Morgan
151,2023-05-14,Empowered 5: Empowered Women - By Corey Garris,,Empowered 5: Empowered Women,Corey Garris
152,2023-05-07,Empowered 4: Spiritual Gifts - By Corey Garris,,Empowered 4: Spiritual Gifts,Corey Garris
153,2023-04-30,Empowered 3: Prophecy - By Ben Folman,,Empowered 3: Prophecy,Ben Folman
154,2023-04-23,Empowered 2: Healing - By Jay Pathak,,Empowered 2: Healing,Jay Pathak
155,2023-04-16,Empowered 1: Revelation - By Corey Garris,,Empowered 1: Revelation,Corey Garris
156,2023-04-09,Beauty From Ashes 8: Easter Sunday - By Corey ...,,Beauty From Ashes 8: Easter Sunday,Corey Garris
157,2023-04-02,Beauty From Ashes 7: the Suffering Servant - B...,,Beauty From Ashes 7: the Suffering Servant,Jay Pathak
158,2023-03-26,Beauty From Ashes 6: Choosing To Be A Servant ...,,Beauty From Ashes 6: Choosing To Be A Servant,Corey Garris
159,2023-03-19,Beauty From Ashes 5: Our Troubles Are His Triu...,,Beauty From Ashes 5: Our Troubles Are His Triu...,Corey Garris
160,2023-03-12,Beauty From Ashes 4: The Hope Of New Justice -...,,Beauty From Ashes 4: The Hope Of New Justice,Jay Pathak
161,2023-03-05,Beauty From Ashes 3: The Nations Will Bow - By...,,Beauty From Ashes 3: The Nations Will Bow,Corey Garris
162,2023-02-26,Beauty From Ashes 2: Immanuel,,Beauty From Ashes 2: Immanuel,Jay Pathak
163,2023-02-12,"Better Choices, Better Life 6: Leaders Worth F...",,"Better Choices, Better Life 6: Leaders Worth F...",Corey Garris
164,2023-02-05,"Better Choices, Better Life 5: Relationships F...",,"Better Choices, Better Life 5: Relationships F...",Jay Pathak
165,2023-01-29,"Better Choices, Better Life 4: Living For A Fu...",,"Better Choices, Better Life 4: Living For A Fu...",Corey Garris
166,2023-01-22,"Better Choices, Better Life 3: Seeing What's H...",,"Better Choices, Better Life 3: Seeing What's H...",Jay Pathak
167,2023-01-15,"Better Choices, Better Life 2: Making Peace Wi...",,"Better Choices, Better Life 2: Making Peace Wi...",Corey Garris
168,2023-01-08,Better Choices Better Life 1: Why is making go...,,Better Choices Better Life 1: Why is making go...,Corey Garris
169,2023-01-01,New Years 2023,,New Years 2023,Jay Pathak
170,2022-12-18,Advent Week 4 Love: Zechariah,,Advent Week 4 Love: Zechariah,Jay Pathak
171,2022-12-11,Advent Week 3 Joy: The Magi,,Advent Week 3 Joy: The Magi,Corey Garris
172,2022-12-04,Advent Week 2 Love: Mary,,Advent Week 2 Love: Mary,Becca Knudsen
173,2022-11-27,Advent Week 1 Hope: John The Baptist,,Advent Week 1 Hope: John The Baptist,Corey Garris
174,2022-11-20,One-Day Offering 2023,,One-Day Offering 2023,Jay Pathak
175,2022-11-13,Wired For Joy Week 7: Appreciation,,Wired For Joy Week 7: Appreciation,Corey Garris
176,2022-11-06,Wired For Joy Week 6: Relational Joy,,Wired For Joy Week 6: Relational Joy,Danielle Pathak
177,2022-10-30,Wired For Joy Week 5: Contagious Joy,,Wired For Joy Week 5: Contagious Joy,Jay Pathak
178,2022-10-23,Wired For Joy Week 4: Proximity to Presence,,Wired For Joy Week 4: Proximity to Presence,Corey Garris
179,2022-10-16,Wired For Joy Week 3: Your Joyful Identity,,Wired For Joy Week 3: Your Joyful Identity,Jay Pathak
180,2022-10-09,Wired For Joy Week 2: The Presence of Joy,,Wired For Joy Week 2: The Presence of Joy,Corey Garris
181,2022-10-02,Wired For Joy Week 1: Rethinking Joy,,Wired For Joy Week 1: Rethinking Joy,Anabeth Morgan
182,2022-09-25,Baptism Sunday,,Baptism Sunday,Corey Garris
183,2022-09-18,First John Week 6: Trust,,First John Week 6: Trust,Jay Pathak
184,2022-09-11,First John Week 5: Love Part 2,,First John Week 5: Love Part 2,Corey Garris
185,2022-09-04,First John Week 4: Love Part 1,,First John Week 4: Love Part 1,Jay Pathak
186,2022-08-28,First John Week 3: Light Part 2,,First John Week 3: Light Part 2,Corey Garris
187,2022-08-21,First John Week 2: Light Part 1,,First John Week 2: Light Part 1,Jay Pathak
188,2022-08-14,First John Week 1: Why Believe?,,First John Week 1: Why Believe?,Corey Garris
189,2022-08-07,Anchor Week 13: Final Week - Review,,Anchor Week 13: Final Week - Review,Jay Pathak
190,2022-07-31,Anchor Week 12: The Lord's Prayer (Lord's Day ...,,Anchor Week 12: The Lord's Prayer (Lord's Day ...,Jay Pathak
191,2022-07-24,Anchor Week 11: The Ten Commandments (Lord's D...,,Anchor Week 11: The Ten Commandments (Lord's D...,Ryan Rowlette
192,2022-07-17,Anchor Week 10: Good Works & Conversion (Lord'...,,Anchor Week 10: Good Works & Conversion (Lord'...,Ben Folman
193,2022-07-10,"Anchor Week 9: Preaching, Sacraments & Discipl...",,"Anchor Week 9: Preaching, Sacraments & Discipl...",Corey Garris
194,2022-07-03,Anchor Week 8: Justification & Good Works (Lor...,,Anchor Week 8: Justification & Good Works (Lor...,Jay Pathak
195,2022-06-26,Anchor Week 7: God the Holy Spirit (Lord's Day...,,Anchor Week 7: God the Holy Spirit (Lord's Day...,Corey Garris
196,2022-06-19,Anchor Week 6: God the Son (Lord's Days 11-19),,Anchor Week 6: God the Son (Lord's Days 11-19),Corey Garris
197,2022-06-12,Anchor Week 5: The Trinity & God the Father (L...,,Anchor Week 5: The Trinity & God the Father (L...,Jay Pathak